version: "3.9"
services:
  backend:
    build: ./backend
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: base64:xxxxxxxxxxxxxx
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: react_app
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
